### PR TITLE
Adding 'create' verb to proxy-clusterrole

### PR DESCRIPTION
**Pull request by joedborg**
Fixing https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/696

### CODE REVIEW

**Comment by Cynerva** [comment]
The template change looks good. More work is needed to handle upgrades properly.

As noted in [this comment](https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/696#issuecomment-453541725), the RBAC template is never applied when upgrading from an earlier version of the charm that did not have it. Specifically:
1. `config.changed.authorization-mode` is only set on initial install or when the config changes, not on upgrades, so
2. [switch_auth_mode](https://github.com/juju-solutions/kubernetes/blob/293a28060fcdbda1eb4368a78f0be03880cb9f8e/cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py#L1084) handler never runs, so
3. `kubernetes-master.create.rbac` state is never set, so
4. [create_rbac_resources](https://github.com/juju-solutions/kubernetes/blob/293a28060fcdbda1eb4368a78f0be03880cb9f8e/cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py#L1104) handler never runs.

I would recommend adding something to the [upgrade-charm hook handler](https://github.com/juju-solutions/kubernetes/blob/293a28060fcdbda1eb4368a78f0be03880cb9f8e/cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py#L138) to solve this. Specifically, I think you need to do what [this code](https://github.com/juju-solutions/kubernetes/blob/293a28060fcdbda1eb4368a78f0be03880cb9f8e/cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py#L1090-L1092) is doing.

**Comment by joedborg** [comment]
Hi @Cynerva, I had something in place before the merge but wasn't sure if I should keep it (so I didn't).  On the line below https://github.com/juju-solutions/kubernetes/blob/293a28060fcdbda1eb4368a78f0be03880cb9f8e/cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py#L162 I put `set_state('config.changed.authorization-mode')`.  Do you think this is a good way to solve it?

**Comment by Cynerva** [comment]
That can work, but the `config.changed.*` states are normally set and removed in a specific way ([link](https://github.com/juju-solutions/layer-basic/blob/baf582236a7b946da4cd140fd6532a2e0c2774d5/lib/charms/layer/basic.py#L227-L259)). I think it may lead to confusion later on if we're manually setting one config.changed state on upgrade, but not others.

I'd recommend calling `switch_auth_mode()` directly instead.

But for this to work, you'll also need to remove this `data_changed` guard:
https://github.com/juju-solutions/kubernetes/blob/293a28060fcdbda1eb4368a78f0be03880cb9f8e/cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py#L1088

Otherwise, the inner code won't run on upgrade-charm because the authorization-mode hasn't actually changed. I think it's safe to just remove it entirely.

**Comment by joedborg** [comment]
How do they look @Cynerva ?

**Comment by Cynerva** [comment]
LGTM. Thanks!

**Pull request merged**
